# Generated by Django 4.1.3 on 2022-11-11 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='bank',
            field=models.CharField(choices=[('BANCO NACION', 'BANCO NACION'), ('BANCO SANTANDER', 'BANCO SANTANDER'), ('BANCO GALICIA', 'BANCO GALICIA')], default='BANCO NACION', max_length=20),
            preserve_default=False,
        ),
    ]
