# Generated by Django 4.1.3 on 2022-11-22 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccounts', '0003_alter_bankaccount_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 22, 12, 21, 20, 712573)),
        ),
    ]
