# Generated by Django 4.1.3 on 2022-11-22 15:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccounts', '0005_remove_bankaccount_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 22, 12, 32, 4, 171607)),
        ),
    ]
