# Generated by Django 4.1.3 on 2023-01-03 17:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccounts', '0041_alter_bankaccount_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankaccount',
            name='bank',
            field=models.CharField(choices=[('ICBC', 'ICBC'), ('BANCO NACION', 'BANCO NACION'), ('BANCO SANTANDER', 'BANCO SANTANDER'), ('BANCO GALICIA', 'BANCO GALICIA')], max_length=20),
        ),
        migrations.AlterField(
            model_name='bankaccount',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 3, 14, 21, 43, 32301)),
        ),
    ]
