# Generated by Django 4.1.3 on 2022-11-22 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_deposit_extraction_delete_deposit_extraction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transference',
            name='receiver',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='transference',
            name='sender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
