# Generated by Django 4.1.3 on 2022-11-23 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccounts', '0014_alter_bankaccount_created_on'),
        ('transactions', '0004_transference_receiver_alter_transference_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transference',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bankaccounts.bankaccount'),
        ),
    ]
