# Generated by Django 4.1.3 on 2022-11-23 21:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_alter_historialobject_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialobject',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 23, 18, 23, 47, 379492)),
        ),
    ]
