# Generated by Django 4.1.3 on 2022-11-26 05:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccounts', '0021_alter_bankaccount_created_on'),
        ('transactions', '0011_remove_transference_transference_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exchange',
            name='account',
        ),
        migrations.AddField(
            model_name='exchange',
            name='receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='bankaccounts.bankaccount'),
        ),
        migrations.AddField(
            model_name='exchange',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='bankaccounts.bankaccount'),
        ),
        migrations.AlterField(
            model_name='historialobject',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 26, 2, 52, 46, 520571)),
        ),
        migrations.AlterField(
            model_name='transference',
            name='receiver',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
