# Generated by Django 4.1.3 on 2022-11-26 06:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0020_alter_historialobject_created_on'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialobject',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 26, 3, 17, 9, 408038)),
        ),
    ]
