# Generated by Django 4.1.3 on 2022-12-28 13:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccounts', '0034_alter_bankaccount_created_on'),
        ('transactions', '0024_alter_historialobject_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialobject',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bankaccounts.bankaccount'),
        ),
        migrations.AlterField(
            model_name='historialobject',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 28, 10, 9, 51, 50815)),
        ),
    ]
