# Generated by Django 4.1.3 on 2022-12-29 20:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0025_historialobject_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialobject',
            name='transactiontype',
        ),
        migrations.AlterField(
            model_name='historialobject',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 29, 17, 48, 8, 861516)),
        ),
    ]
