# Generated by Django 4.1.3 on 2022-12-29 20:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0026_remove_historialobject_transactiontype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialobject',
            name='transactiontype',
            field=models.CharField(default='-', max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historialobject',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 29, 17, 48, 44, 503991)),
        ),
    ]
