# Generated by Django 4.1.3 on 2022-12-29 20:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0027_historialobject_transactiontype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialobject',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 29, 17, 50, 34, 628521)),
        ),
        migrations.AlterField(
            model_name='historialobject',
            name='transactiontype',
            field=models.CharField(choices=[('Deposit', 'Deposit'), ('Extraction', 'Extraction'), ('Transference', 'Transference'), ('Exchange', 'Exchange')], max_length=12),
        ),
    ]
