# Generated by Django 4.1.3 on 2022-12-30 01:56

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccounts', '0038_alter_bankaccount_created_on'),
        ('transactions', '0028_alter_historialobject_created_on_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialobject',
            name='account_receiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='secondary', to='bankaccounts.bankaccount'),
        ),
        migrations.AlterField(
            model_name='historialobject',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='main', to='bankaccounts.bankaccount'),
        ),
        migrations.AlterField(
            model_name='historialobject',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 29, 22, 56, 13, 653367)),
        ),
    ]
