# Generated by Django 4.1.3 on 2022-12-30 04:07

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccounts', '0039_alter_bankaccount_created_on'),
        ('transactions', '0029_historialobject_account_receiver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialobject',
            name='account_receiver',
        ),
        migrations.AlterField(
            model_name='historialobject',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bankaccounts.bankaccount'),
        ),
        migrations.AlterField(
            model_name='historialobject',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2022, 12, 30, 1, 7, 43, 116575)),
        ),
        migrations.CreateModel(
            name='HistorialObjectReceived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transactiontype', models.CharField(choices=[('Deposit', 'Deposit'), ('Extraction', 'Extraction'), ('Transference', 'Transference'), ('Exchange', 'Exchange')], max_length=12)),
                ('created_on', models.DateTimeField(default=datetime.datetime(2022, 12, 30, 1, 7, 43, 117831))),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='bankaccounts.bankaccount')),
            ],
        ),
    ]
