# Generated by Django 4.1.3 on 2023-01-03 08:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccounts', '0040_alter_bankaccount_created_on'),
        ('transactions', '0030_remove_historialobject_account_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialobjectreceived',
            name='accountSender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accountSender', to='bankaccounts.bankaccount'),
        ),
        migrations.AlterField(
            model_name='historialobject',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 3, 5, 16, 50, 601999)),
        ),
        migrations.AlterField(
            model_name='historialobjectreceived',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='account', to='bankaccounts.bankaccount'),
        ),
        migrations.AlterField(
            model_name='historialobjectreceived',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 3, 5, 16, 50, 603351)),
        ),
    ]
