# Generated by Django 4.1.3 on 2023-01-03 16:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bankaccounts', '0041_alter_bankaccount_created_on'),
        ('transactions', '0031_historialobjectreceived_accountsender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='historialobject',
            name='accountReceiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accountReceiver', to='bankaccounts.bankaccount'),
        ),
        migrations.AlterField(
            model_name='historialobject',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accountS', to='bankaccounts.bankaccount'),
        ),
        migrations.AlterField(
            model_name='historialobject',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 3, 13, 6, 9, 855967)),
        ),
        migrations.AlterField(
            model_name='historialobjectreceived',
            name='account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='accountR', to='bankaccounts.bankaccount'),
        ),
        migrations.AlterField(
            model_name='historialobjectreceived',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 3, 13, 6, 9, 857648)),
        ),
    ]
