# Generated by Django 4.1.3 on 2023-03-26 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0035_alter_deposit_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialobject',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 26, 15, 4, 41, 851223)),
        ),
        migrations.AlterField(
            model_name='historialobjectreceived',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 26, 15, 4, 41, 852962)),
        ),
    ]
